version: '3'

services:
  alpaca-proxy:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    volumes:
    - ./:/opt/project
    command: python main.py
    ports:
      - "8765:8765"
    environment:
      - IS_PRO=True